package lab_1;

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Grammar grammar = new Grammar();
        Scanner scanner = new Scanner(System.in);
        for (int i = 0; i < 5; i++) {
            System.out.println("Generated string" + " " + (i + 1) + " : " + grammar.generateString());
        }
        FiniteAutomaton finiteAutomaton = grammar.toFiniteAutomaton();
        //finiteAutomaton.displayAutomaton();
        System.out.println(" ");
        System.out.println("Enter a string to check if it belongs to the language (or type 'exit' to quit): ");

        while (true) {
            String inputString = scanner.nextLine();

            // Check if the user wants to exit
            if (inputString.equalsIgnoreCase("exit")) {
                System.out.println("Exiting program.");
                break;
            }

            if (finiteAutomaton.stringBelongsToLanguage(inputString)) {
                System.out.println("The string '" + inputString + "' belongs to the language generated by the grammar.");
            } else {
                System.out.println("The string '" + inputString + "' does not belong to the language generated by the grammar.");
            }
        }
    }
}


